email: "mohammad-haroon.masah@epitech.eu"
description: >-
  "Web Development Student at Epitech Paris. 
  Focused on building modern web applications with HTML, CSS, and JavaScript.
baseurl: "/Portfolio"
url: "https://mohammadmasah.github.io"
theme: minima

header_pages:
  - about.markdown
  - projects.md
  - index.markdown

plugins:
  - jekyll-feed
  - jekyll-relative-links

collections:
  projects:
    output: true
