title: Mohammad Masah Portfolio
email: mohammad-haroon.masah@epitech.eu
description: My professional portfolio
baseurl: "/Portfolio"
url: "https://mohammadmasah.github.io"
theme: minima

header_pages:
- about.markdown
- project-1.md

plugins:
  - jekyll-feed
  - jekyll-relative-links

collections:
  projects:
    output: true