# Site
name: "Mohammad H. Masah"
description: "Student at Epitech | Portfolio"
logo: "assets/images/logo.png"
email: "mohammad-haroon.masah@epitech.eu"

include: ["_pages"]
permalink: /:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
  Mohammad:
    name: "Mohammad H. Masah"
    site: https://mohammadrasah.github.io/Portfolio/
    avatar: /assets/images/avatar1.jpg
    bio: "Student at Epitech | Passionate about software development and creating innovative solutions."
    email: "mohammad-haroon.masah@epitech.eu"
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Mohammad
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Paginate
paginate: 10


